@startuml
[*] --> NoLayout
NoLayout --> LayoutLoaded: Load Layout File
LayoutLoaded --> NoLayout: Load Bad File
LayoutLoaded --> [*]: Exit Simulation

state LayoutLoaded {
    [*] --> SimOFF
    SimOFF --> SimON: Turn Simulation On
    SimON --> SimOFF: Turn Simulation Off
}

}
@enduml